GET http://localhost:7778/api/auth


###
GET http://localhost:7778/api/users


### REGISTER
POST http://localhost:7778/api/auth/register
Content-Type: application/json

{
    "username": "oli",
    "email": "oli@gmail.com",
    "password": "123456"
}


### LOG IN
POST http://localhost:7778/api/auth/login
Content-Type: application/json

{
    "email": "oli@gmail.com",
    "password": "123456"
}


### UPDATE
PATCH http://localhost:7778/api/users/6817de2db27c3d10ccce6bda
Content-Type: application/json

{
    "password": "1234567"
}


### LOGOUT
GET http://localhost:7778/api/auth/logout


### DELETE
DELETE http://localhost:7778/api/users/67db378c19ccfaccb9982968


