GET http://localhost:7778/api/auth


###
GET http://localhost:7778/api/users



### POSTS

### CREATE
POST http://localhost:7778/api/posts/create
Content-Type: application/json

{
  "title": "Test2 Post",
  "description": "Create new Test",
  "username": "ina2",
  "userId": "67bef9a64eaf97cbd6b201b9",
  "categories": ["music", "test2"],
  "photo": "https://pixabay.com/photos/technology-white-space-keyboard-3472295/"
}


### UPDATE
PUT http://localhost:7778/api/posts/67bf0481f1e662f2cac41e91
Content-Type: application/json

{
    "title": "Update new Post2",
    "description": "Update Test1",
    "categories": ["music", "fan"]
}


### DELETE
DELETE http://localhost:7778/api/posts/67b5ccd7ffade804f1da87c2


### GET ALL / SEARCH
GET http://localhost:7778/api/posts?search=Test1


### GET DETAILS POST /:id
GET http://localhost:7778/api/posts/67b5de8aebb9a7353e99fae3

### GET USER POST
GET http://localhost:7778/api/posts?userId=67b5c6e33a6ab3a9957a43d1


### COMMENTS

### CREATE
POST http://localhost:7778/api/comments/create
Content-Type: application/json

{
    "comment": "Comment 3",
    "autor": "ira",
    "postID": "67b5de8aebb9a7353e99fae3",
    "userId": "67b5c6e33a6ab3a9957a43d1"
}

### UPDATE
PUT http://localhost:7778/api/comments/67b5fa45658ab3f4624ca4bf
Content-Type: application/json

{
    "comment": "Comment 1",
    "autor": "ira",
    "postID": "67b5de8aebb9a7353e99fae3",
    "userId": "67b5c6e33a6ab3a9957a43d1"
}

### DELETE
DELETE http://localhost:7778/api/comments/67b60b7f1c0d3a5b06187df5

### GET POST
GET http://localhost:7778/api/posts?postId=67b5de8aebb9a7353e99fae3